<a href="https://colab.research.google.com/github/KoshiBG/Python_for_data_analysis/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22hw_3_2_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%B8_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B8_%D0%B7_%D0%B4%D0%B0%D0%BD%D0%B8%D0%BC%D0%B8_%D1%83_Pandas_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання до теми "Основи роботи з даними у Pandas"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_path = "/content/drive/MyDrive/code/data/supermarket_sales.csv"
df = pd.read_csv(data_path)

In [ ]:
df.iloc[[0, 2, 4], [1, 2]]

  Branch    City
0      A  Yangon
2      A  Yangon
4      A  Yangon

In [ ]:
df.iloc[0:5, 1:3]

  Branch       City
0      A     Yangon
1      C  Naypyitaw
2      A     Yangon
3      A     Yangon
4      A     Yangon

1. За допомогою бібліотеки Pandas виведіть перші 4 і останні 4 записи у наборі даних (це дві окремі команди). Треба саме 4! Не 5.

In [ ]:
df[:4]   # Можно вивести перші 4 через метод head(), але як на мене, в цьому варіанті менше коду)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4

In [ ]:
df.tail(4)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,3/2/2019,17:16,Ewallet,973.80,4.761905,48.690,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.592,33.432,2/9/2019,13:22,Cash,31.84,4.761905,1.592,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.291,69.111,2/22/2019,15:33,Cash,65.82,4.761905,3.291,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.919,649.299,2/18/2019,13:28,Cash,618.38,4.761905,30.919,6.6

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1F5XlzBOOTMsedpsYqz6NnXjIPTDe6jpx)

2. Виведіть рядки даних з індексами з 615 по 619 включно.

In [ ]:
df[615:620]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
615,509-29-3912,A,Yangon,Member,Female,Sports and travel,38.72,9,17.4240,365.9040,3/20/2019,12:24,Ewallet,348.48,4.761905,17.4240,4.2
616,327-40-9673,B,Mandalay,Member,Male,Sports and travel,72.60,6,21.7800,457.3800,1/13/2019,19:51,Cash,435.60,4.761905,21.7800,6.9
617,840-19-2096,C,Naypyitaw,Member,Male,Electronic accessories,87.91,5,21.9775,461.5275,3/14/2019,18:10,Ewallet,439.55,4.761905,21.9775,4.4
618,828-46-6863,A,Yangon,Member,Male,Food and beverages,98.53,6,29.5590,620.7390,1/23/2019,11:22,Credit card,591.18,4.761905,29.5590,4.0
619,641-96-3695,C,Naypyitaw,Member,Female,Fashion accessories,43.46,6,13.0380,273.7980,2/7/2019,17:55,Ewallet,260.76,4.761905,13.0380,8.5

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1Otufe_TXRmjZxWigzBiVBLCAVUfEReXM)

3. Виведіть назви колонок у наборі даних разом з їхніми типами. Це можна зробити кількома способами, важливо аби в результаті були назви колонок і відповідні їм типи.

In [ ]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

Очікуваний результат (один з можливих форматів):

![](https://drive.google.com/uc?export=view&id=1ASh6-S-_f3X9fTQAPIvnHMFZamTBjNkL)

4. Користуючись методом `DataFrame.describe()` виявіть 1, 25, 50, 75 і 99 персентилі колонки `gross income`. Знайдіть, яке значення відповідає 75отму персентилю цієї колонки і що це означає? Як би Ви його пояснили простими словами колегам? Відповідь напишіть текстом в окремій клітинці типу Markdown.

In [ ]:
description = df['gross income'].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.99])
display(description)

count    1000.000000
mean       15.379369
std        11.708825
min         0.508500
10%         3.243000
25%         5.924875
50%        12.088000
75%        22.445250
99%        45.250750
max        49.650000
Name: gross income, dtype: float64

75-й персентиль: 75% даних знаходиться нижче значення 22.44

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1bDa1YFUWDsPm78Lnpy2geQND8M1HEQiT)

5. Виведіть кількість інвойсів за кожним унікальним містом в наборі даних.

  Підказка: інвойс - це один рядок в цьому наборі даних, ми можемо цим скористатись аби швидко отримати відповідь.

In [ ]:
invoice_counts = df['City'].value_counts()
display(invoice_counts)

City
Yangon       340
Mandalay     332
Naypyitaw    328
Name: count, dtype: int64

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1G8c6M875NOW7oU3OtZegTOnyD2y8lhAV)

6. Виведіть, який відсоток інвойсів припадає на кожне унікальне місто.

In [ ]:
invoice_counts/invoice_counts.sum()

City
Yangon       0.340
Mandalay     0.332
Naypyitaw    0.328
Name: count, dtype: float64

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1yZZpWhL2y8DX9rSRioYCRh1VbJgcf3fY)

7.1. Використовуючи фільтрацію даних, знайдіть середнє значення `gross income` для міст `Yangon` та `Mandalay`. В якому місті воно більше?

7.2 Сформулюйте 3 гіпотези, чому в одному місті gross income вище, як можна дізнатись чи правдива ця гіпотеза з використанням даних (наявних і додаткових), та як висновки з цих гіпотез можна використати для прийняття рішень як підвищити прибуток в мережі супермаркетів. Відповідь напишіть текстом в окремій клітинці типу Markdown.

Це завдання - на продуктове мислення. Якщо не знаєте, які гіпотези сформулювати - напишіть ті, які здаються вам зовсім примітивними. Важливо навчитись висловлювати свої гіпотези щодо даних, і з часом та досвідом вони будуть ставати щоразу глибше і точніше. Весь аналіз даних будується на тому, що ми перевіряємо певні гіпотези та робимо висновки і рекоемндації на основі своїх досліджень.

In [ ]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [ ]:
# Фільтрація даних для міст Yangon та Mandalay
filtered_data = df[df['City'].isin(['Yangon', 'Mandalay'])]

# Обчислення середнього значення gross income для кожного міста
average_gross_income = filtered_data.groupby('City')['gross income'].mean()

# Виведення результатів
print(average_gross_income)

City
Mandalay    15.232024
Yangon      14.874001
Name: gross income, dtype: float64

In [ ]:
average_gross_income/average_gross_income.sum()

City
Mandalay    0.505946
Yangon      0.494054
Name: gross income, dtype: float64

Відсоткове співвідношення "gross income" .


В місті Mandalay дохід більше на 1%. На цей чинник можуть впливати наступні наявні данні:
1.Branch (Філія): Різні філії можуть мати різні обсяги продажів, залежно від їхнього розташування, розміру та кількості клієнтів.
2.City (Місто): Розташування магазину в різних містах може впливати на валовий дохід через відмінності в попиті, купівельній спроможності клієнтів і конкуренції.
3.Customer type (Тип клієнта): Різні типи клієнтів (наприклад, нові або постійні клієнти) можуть мати різні купівельні звички, що впливає на загальний дохід
4.Gender (Стать): Можливо, стать клієнтів може впливати на типи продуктів, які вони купують, і їх загальну вартість покупок.
5.Product line (Продуктова лінійка): Різні продуктові лінійки можуть мати різні рівні популярності та цінові категорії, що безпосередньо впливає на валовий дохід.
6.Unit price (Ціна за одиницю): Ціна продукту безпосередньо впливає на валовий дохід, оскільки більші ціни зазвичай означають більший дохід за одиницю товару.
7.Date (Дата): Продажі можуть варіюватися в залежності від днів тижня, місяців або сезонів, що впливає на валовий дохід.
8.Time (Час): Час доби може впливати на кількість продажів, наприклад, певні години можуть бути більш популярними для покупок.
9.Payment (Спосіб оплати): Різні способи оплати можуть впливати на зручність покупок і, як наслідок, на валовий дохід.

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1JdXUmK46WcoXUJYP7NS2SJlr2XjBbpQ8)

8. Для продовження дослідження різниці у прибутках в магазинах давайте зʼясуємо, чи відрізняється маржа ('gross margin percentage') для різних інвойсів в магазині? Перевірте це програмно на даних виходячи з того функціоналу, який ми вже пройшли у лекціях.

Дайте на основі отриманого результату відповідь: "У всіх всіх інвойсах однакова маржа" або "Маржа відрізняється для різних інвойсів".

In [ ]:
description = df['gross margin percentage'].describe()
display(description)

count    1000.000000
mean        4.761905
std         0.000000
min         4.761905
25%         4.761905
50%         4.761905
75%         4.761905
max         4.761905
Name: gross margin percentage, dtype: float64

Очікуваний результат: відповідь щодо маржі в усіх інвойсах на основі отриманих результатів

"У всіх всіх інвойсах однакова маржа"

9. Врахувуючи висновок в попередньому завданні, дослідимо як продаються в цих містах різні категорії товарів. Виведіть відсотковий розпоіділ кількості інвойсів по категоріям товарів `Product line` в містах `Yangon` та `Mandalay`.

In [ ]:
# Відфільтруємо дані для міст Yangon та Mandalay

filtered_data = df[df['City'].isin(['Yangon', 'Mandalay'])]

# Порахуємо кількість інвойсів по кожній категорії товарів для кожного міста

invoice_counts = filtered_data.groupby(['City', 'Product line']).size()

#Обчислення відсоткового розподілу

percentage_distribution = invoice_counts/invoice_counts.sum()*100
print(percentage_distribution)

City      Product line
Mandalay  Electronic accessories    8.184524
          Fashion accessories       9.226190
          Food and beverages        7.440476
          Health and beauty         7.886905
          Home and lifestyle        7.440476
          Sports and travel         9.226190
Yangon    Electronic accessories    8.928571
          Fashion accessories       7.589286
          Food and beverages        8.630952
          Health and beauty         6.994048
          Home and lifestyle        9.672619
          Sports and travel         8.779762
dtype: float64

Очікуваний результат для кожного з міст:

![](https://drive.google.com/uc?export=view&id=1IbG58YK5KVqC-wCnllF1btgEgfWTbi_O)

![](https://drive.google.com/uc?export=view&id=1aKOkLmlMq1sOh4GbwyaQyjfhNJzdU4Yh)